interface
      SUBROUTINE AIRSEA (KIJS, KIJL, &
&                        HALP, U10, U10DIR, TAUW, TAUWDIR, RNFAC,  &
&                        US, Z0, Z0B, CHRNCK, ICODE_WND, IUSFG)

 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM, ONLY : NANG ,NFRE
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL, ICODE_WND, IUSFG
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT (IN) :: HALP, U10DIR, TAUW, TAUWDIR, RNFAC
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT (INOUT) :: U10, US
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT (OUT) :: Z0, Z0B, CHRNCK
 END SUBROUTINE AIRSEA
end interface
