interface
SUBROUTINE ALPHAP_TAIL(KIJS, KIJL, FL1, ALPHAP)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM , ONLY : NANG ,NFRE
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(IN) :: FL1
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: ALPHAP
END SUBROUTINE ALPHAP_TAIL
end interface
