interface
SUBROUTINE CAL_SECOND_ORDER_SPEC(KIJS, KIJL, F1, WAVNUM, DEPTH, SIG)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 use yowparam, only:&
 & nang,&
 & nfre
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(INOUT) :: F1
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NFRE), INTENT(IN) :: WAVNUM
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: DEPTH
 REAL(KIND=JWRB), INTENT(IN) :: SIG
END SUBROUTINE CAL_SECOND_ORDER_SPEC
end interface
