interface
SUBROUTINE CDUSTARZ0(KIJS, KIJL, U10, ZREF, CD, USTAR, Z0)
use parkind_wave, only:&
 & jwim,&
 & jwrb
INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
REAL(KIND=JWRB), INTENT(IN) :: ZREF
REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: U10
REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: CD, USTAR, Z0
END SUBROUTINE CDUSTARZ0
end interface
