interface
 SUBROUTINE CIMSSTRN(KIJS, KIJL, FL1, WAVNUM, DEPTH, CITHICK, STRN)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM , ONLY : NANG ,NFRE
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(IN) :: FL1
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NFRE), INTENT(IN) :: WAVNUM
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: DEPTH
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: CITHICK
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: STRN
 END SUBROUTINE CIMSSTRN
end interface
