interface
 SUBROUTINE FINDB (NDIM, NBOUN, BLATB, BLNGB, IJARB, &
 & NPROC, NSTART, NEND, IRANK)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: NDIM, NBOUN, NPROC, IRANK
 INTEGER(KIND=JWIM), DIMENSION(NPROC), INTENT(IN) :: NSTART,NEND
 INTEGER(KIND=JWIM), DIMENSION(NDIM), INTENT(INOUT) :: IJARB
 REAL(KIND=JWRB), DIMENSION(NDIM),INTENT(IN) :: BLATB, BLNGB
 END SUBROUTINE FINDB
end interface
