interface
 SUBROUTINE FRCUTINDEX (KIJS, KIJL, FM, FMWS, UFRIC, CICOVER, &
 & MIJ, RHOWGDFTH)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM , ONLY : NFRE
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 INTEGER(KIND=JWIM), INTENT(OUT) :: MIJ(KIJS:KIJL)
 REAL(KIND=JWRB),DIMENSION(KIJS:KIJL), INTENT(IN) :: FM, FMWS, UFRIC, CICOVER
 REAL(KIND=JWRB),DIMENSION(KIJS:KIJL,NFRE), INTENT(OUT) :: RHOWGDFTH
 END SUBROUTINE FRCUTINDEX
end interface
