interface
SUBROUTINE GET_PRESET_WGRIB_TEMPLATE(CT,IGRIB_HANDLE)
 use parkind_wave, only:&
 & jwim
 CHARACTER(LEN=1), INTENT(IN) :: CT
 INTEGER(KIND=JWIM), INTENT(OUT) :: IGRIB_HANDLE
END SUBROUTINE GET_PRESET_WGRIB_TEMPLATE
end interface
