interface
SUBROUTINE GETSTRESS(BLK2LOC, WVENVI, FF_NOW, NEMO2WAM,        &
     &                     NBLKS, NBLKE, IREAD)
 use parkind_wave, only:&
 & jwim
 USE YOWDRVTYPE , ONLY : WVGRIDLOC, ENVIRONMENT, FORCING_FIELDS, OCEAN2WAVE
 use yowgrid , only:&
 & nproma_wam,&
 & nchnk
 use yowmpp , only:&
 & nproc
    TYPE(WVGRIDLOC), INTENT(IN) :: BLK2LOC
      TYPE(ENVIRONMENT), INTENT(INOUT) :: WVENVI
      TYPE(FORCING_FIELDS), INTENT(INOUT) :: FF_NOW
      TYPE(OCEAN2WAVE), INTENT(INOUT) :: NEMO2WAM
      INTEGER(KIND=JWIM), INTENT(IN) :: IREAD
      INTEGER(KIND=JWIM),DIMENSION(NPROC), INTENT(IN) :: NBLKS, NBLKE
END SUBROUTINE GETSTRESS
end interface
