interface
SUBROUTINE GRADI (KIJS, KIJL, NINF, NSUP, IREFRA,   &
 &                  BLK2GLO,                        &
 &                  DPTHEXT, UEXT, VEXT,            &
 &                  DDPHI, DDLAM, DUPHI,            &
 &                  DULAM, DVPHI, DVLAM)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWDRVTYPE , ONLY : WVGRIDGLO
 USE YOWPARAM , ONLY : NIBLO
INTEGER(KIND=JWIM), INTENT(IN) :: KIJS
      INTEGER(KIND=JWIM), INTENT(IN) :: KIJL
      INTEGER(KIND=JWIM), INTENT(IN) :: NINF
      INTEGER(KIND=JWIM), INTENT(IN) :: NSUP
      INTEGER(KIND=JWIM), INTENT(IN) :: IREFRA
      TYPE(WVGRIDGLO), INTENT(IN) :: BLK2GLO
      REAL(KIND=JWRB), DIMENSION(NINF:NSUP+1), INTENT(IN) :: DPTHEXT
      REAL(KIND=JWRB), DIMENSION(NINF:NSUP+1), INTENT(IN) :: UEXT
      REAL(KIND=JWRB), DIMENSION(NINF:NSUP+1), INTENT(IN) :: VEXT

      REAL(KIND=JWRB),DIMENSION(KIJS:KIJL), INTENT(OUT) :: DDPHI
      REAL(KIND=JWRB),DIMENSION(KIJS:KIJL), INTENT(OUT) :: DDLAM
      REAL(KIND=JWRB),DIMENSION(KIJS:KIJL), INTENT(OUT) :: DUPHI
      REAL(KIND=JWRB),DIMENSION(KIJS:KIJL), INTENT(OUT) :: DULAM
      REAL(KIND=JWRB),DIMENSION(KIJS:KIJL), INTENT(OUT) :: DVPHI
      REAL(KIND=JWRB),DIMENSION(KIJS:KIJL), INTENT(OUT) :: DVLAM
END SUBROUTINE GRADI
end interface
