interface
 SUBROUTINE GRSTNAME (CDATED, CDATEF, IFCST, FILEID, KCPLEN, CPAD, &
 & FILENAME)
 use parkind_wave, only:&
 & jwim
 CHARACTER(LEN=14), INTENT(IN) :: CDATED, CDATEF
 INTEGER(KIND=JWIM), INTENT(IN) :: IFCST
 CHARACTER(LEN=3), INTENT(IN) :: FILEID
 INTEGER(KIND=JWIM), INTENT(IN) :: KCPLEN
 CHARACTER(LEN=*), INTENT(IN) :: CPAD
 CHARACTER(LEN=*), INTENT(OUT) :: FILENAME
 END SUBROUTINE GRSTNAME
end interface
