interface
 SUBROUTINE H_MAX(C3,C4,XNSLC,KIJS,KIJL,AA,BB,HMAXN,SIG_HM)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: C3, C4, XNSLC
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: AA, BB, HMAXN, SIG_HM
 END SUBROUTINE H_MAX
end interface
