interface
SUBROUTINE INIT_FIELDG(BLK2LOC, LLINIALL, LLOCAL, &
 & NXS, NXE, NYS, NYE, FIELDG)
 use parkind_wave, only:&
 & jwim
 USE YOWDRVTYPE , ONLY : WVGRIDLOC, FORCING_FIELDS
 use yowgrid , only:&
 & nproma_wam,&
 & nchnk
    TYPE(WVGRIDLOC), INTENT(IN) :: BLK2LOC
      LOGICAL, INTENT(IN) :: LLINIALL, LLOCAL
      INTEGER(KIND=JWIM), INTENT(IN) :: NXS, NXE, NYS, NYE
      TYPE(FORCING_FIELDS), INTENT(INOUT) :: FIELDG
END SUBROUTINE INIT_FIELDG
end interface
