interface
 SUBROUTINE INTSPEC (NFRE, NANG, ML, KL, FR, DEL12, DEL1L, &
 & F1, FMEAN1, EMEAN1, THETM1, &
 & F2, FMEAN2, EMEAN2, THETM2, &
 & FL, FMEAN, EMEAN, THETM )
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: NFRE, NANG, ML, KL
 REAL(KIND=JWRB), INTENT(IN) :: DEL12, DEL1L
 REAL(KIND=JWRB), INTENT(IN) :: FMEAN1, EMEAN1, THETM1
 REAL(KIND=JWRB), INTENT(IN) :: FMEAN2, EMEAN2, THETM2
 REAL(KIND=JWRB), INTENT(OUT) :: FMEAN, EMEAN, THETM
 REAL(KIND=JWRB), DIMENSION(NFRE), INTENT(IN) :: FR
 REAL(KIND=JWRB), DIMENSION(NANG,NFRE), INTENT(IN) :: F1
 REAL(KIND=JWRB), DIMENSION(NANG,NFRE), INTENT(IN) :: F2
 REAL(KIND=JWRB), DIMENSION(NANG,NFRE), INTENT(OUT) :: FL
 END SUBROUTINE INTSPEC
end interface
