interface
SUBROUTINE INWGRIB (FILNM, IREAD, CDATE, IPARAM, KZLEV,  &
     &                    NXS, NXE, NYS, NYE, FIELDG, FIELD)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
USE YOWDRVTYPE, ONLY:FORCING_FIELDS
CHARACTER(LEN=24), INTENT(IN) :: FILNM
      INTEGER(KIND=JWIM), INTENT(IN) :: IREAD
      CHARACTER(LEN=14), INTENT(OUT) :: CDATE
      INTEGER(KIND=JWIM), INTENT(OUT) :: IPARAM, KZLEV
      INTEGER(KIND=JWIM), INTENT(IN) :: NXS, NXE, NYS, NYE
      TYPE(FORCING_FIELDS), INTENT(IN) :: FIELDG
      REAL(KIND=JWRB), INTENT(OUT) :: FIELD(NXS:NXE, NYS:NYE)
 END SUBROUTINE INWGRIB
end interface
