interface
 SUBROUTINE JONSWAP (ALPHAJ, ZGAMMA, SA, SB, FP, KIJS, KIJL, ET)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM , ONLY : NFRE
 REAL(KIND=JWRB), INTENT(IN) :: ZGAMMA, SA, SB
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: ALPHAJ, FP
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NFRE), INTENT(OUT) :: ET
 END SUBROUTINE JONSWAP
end interface
