interface
 SUBROUTINE KGRIBSIZE(IU06, KLEN, ISIZE, CALLINGSUB)
 use parkind_wave, only:&
 & jwim
 USE YOWGRIB, ONLY : JPKSIZE_T
 INTEGER(KIND=JWIM) :: IU06
 INTEGER(KIND=JWIM) :: ISIZE
 INTEGER(KIND=JPKSIZE_T) :: KLEN
 CHARACTER (LEN=*) :: CALLINGSUB
 END SUBROUTINE KGRIBSIZE
end interface
