interface
 SUBROUTINE MBOUNF (IU03, IU10, IU20, IFORM, IINPC)
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM), INTENT(IN) :: IU03, IU10, IU20, IFORM
 INTEGER(KIND=JWIM), INTENT(OUT) :: IINPC
 END SUBROUTINE MBOUNF
end interface
