interface
 SUBROUTINE MBOXB (NBOUN, AMOWEB, AMOSOB, AMOEAB, &
 & AMONOB, BLATB, BLNGB)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPRPROC, ONLY : NBMAX
 INTEGER(KIND=JWIM), INTENT(OUT) :: NBOUN
 REAL(KIND=JWRB), INTENT(IN) :: AMOWEB, AMOSOB, AMOEAB, AMONOB
 REAL(KIND=JWRB), DIMENSION(NBMAX), INTENT(INOUT) :: BLNGB, BLATB
 END SUBROUTINE MBOXB
end interface
