interface
 SUBROUTINE MEANS( &
 & NSPEC , MPART , NPART , NANG, NFRE , &
 & SPEC , PART , &
 & MEANE , MEANANG , MEANFRE , PKFRE , &
 & SUM0 , SUMX0 , SUMY0 )
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM) :: NSPEC, MPART, NPART(NSPEC), NANG, NFRE
 REAL(KIND=JWRB) :: SPEC(0:NSPEC,NANG,NFRE)
 INTEGER(KIND=JWIM) :: PART(NSPEC,NANG,NFRE)
 REAL(KIND=JWRB) :: MEANE(NSPEC,MPART), &
 & MEANANG(NSPEC,MPART), MEANFRE(NSPEC,MPART)
 REAL(KIND=JWRB) :: PKFRE(NSPEC,MPART)
 REAL(KIND=JWRB) :: SUM0(NSPEC,MPART), &
 & SUMX0(NSPEC,MPART), SUMY0(NSPEC,MPART)
 END SUBROUTINE MEANS
end interface
