interface
 SUBROUTINE MNINTW ( &
 & NSPECW, MPARTSW, &
 & NPARTW, NIPARTINFW, &
 & NINTW)
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM) :: NSPECW , MPARTSW
 INTEGER(KIND=JWIM) :: NPARTW(NSPECW) , NINTW(NSPECW), &
 & NIPARTINFW(NSPECW,MPARTSW)
 END SUBROUTINE MNINTW
end interface
