interface
SUBROUTINE MPBCASTGRID(IU06, ISEND, ITAG)
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM), INTENT(IN) :: IU06, ISEND
 INTEGER(KIND=JWIM), INTENT(INOUT) :: ITAG
END SUBROUTINE MPBCASTGRID
end interface
