interface
 SUBROUTINE MPBCASTINTFLD(ISEND, ITAG, NXF, NYF, IFIELD)
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM), INTENT(IN) :: ISEND, NXF, NYF
 INTEGER(KIND=JWIM), INTENT(INOUT) :: ITAG
 INTEGER(KIND=JWIM),DIMENSION(NXF,NYF), INTENT(INOUT) :: IFIELD
 END SUBROUTINE MPBCASTINTFLD
end interface
