interface
SUBROUTINE MPFLDTOIFS(IJS, IJL, BLK2GLO, NWVFIELDS, BLOCK,       &
 &                    GRID, DEFVAL, MASK_OUT, LLGLOBAL)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWDRVTYPE , ONLY : WVGRIDGLO
 USE YOWPARAM , ONLY : NGX ,NGY ,NIBLO
INTEGER(KIND=JWIM), INTENT(IN) :: IJS, IJL
      TYPE(WVGRIDGLO), INTENT(IN) :: BLK2GLO
      INTEGER(KIND=JWIM), INTENT(IN) :: NWVFIELDS
      REAL(KIND=JWRB), DIMENSION(IJS:IJL,NWVFIELDS), INTENT(IN) :: BLOCK
      REAL(KIND=JWRB), DIMENSION(:,:,:), INTENT(INOUT) :: GRID
      REAL(KIND=JWRB), DIMENSION(NWVFIELDS), INTENT(IN) :: DEFVAL
      INTEGER(KIND=JWIM), INTENT(IN) :: MASK_OUT(NGX,NGY)
      LOGICAL, INTENT(OUT) :: LLGLOBAL
END SUBROUTINE MPFLDTOIFS
end interface
