interface
 SUBROUTINE MPGATHERSCFLD(IRECV, NBLKS, NBLKE, FIELD, NLEN)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 use yowmpp , only:&
 & nproc
 INTEGER(KIND=JWIM), INTENT(IN) :: IRECV
 INTEGER(KIND=JWIM), INTENT(IN) :: NLEN
 INTEGER(KIND=JWIM), DIMENSION(NPROC), INTENT(IN) :: NBLKS, NBLKE
 REAL(KIND=JWRB), DIMENSION(NLEN), INTENT(INOUT) :: FIELD
 END SUBROUTINE MPGATHERSCFLD
end interface
