interface
 SUBROUTINE MSTART (IOPTI, FETCH, FRMAX, THETAQ, &
 & FM, ALFA, ZGAMMA, SA, SB, &
 & KIJS, KIJL, FL1, &
 & WSWAVE, WDWAVE)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM , ONLY : NANG ,NFRE
 INTEGER(KIND=JWIM), INTENT(IN) :: IOPTI
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), INTENT(IN) :: FETCH, FRMAX, THETAQ
 REAL(KIND=JWRB), INTENT(IN) :: FM, ALFA, ZGAMMA, SA, SB
 REAL(KIND=JWRB),DIMENSION(KIJS:KIJL), INTENT(IN) :: WSWAVE, WDWAVE
 REAL(KIND=JWRB),DIMENSION(KIJS:KIJL, NANG, NFRE), INTENT(OUT) :: FL1
 END SUBROUTINE MSTART
end interface
