interface
SUBROUTINE MSWELL (KIJS, KIJL, IFROMIJ, JFROMIJ, NXS, NXE, NYS, NYE, FIELDG, FL1)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWDRVTYPE , ONLY : WVGRIDLOC, FORCING_FIELDS
 USE YOWPARAM , ONLY : NANG ,NFRE
INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      INTEGER(KIND=JWIM), DIMENSION(KIJS:KIJL), INTENT(IN) :: IFROMIJ, JFROMIJ
      INTEGER(KIND=JWIM), INTENT(IN) :: NXS, NXE, NYS, NYE
      TYPE(FORCING_FIELDS), INTENT(IN) :: FIELDG
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL, NANG, NFRE), INTENT(OUT) :: FL1
 END SUBROUTINE MSWELL
end interface
