interface
SUBROUTINE NEWWIND (CDATE, CDATEWH, LLNEWFILE,           &
 &                  WVPRPT, FF_NOW, FF_NEXT)
 USE YOWDRVTYPE , ONLY : FREQUENCY, FORCING_FIELDS
 USE YOWGRID , ONLY : NPROMA_WAM, NCHNK
 USE YOWPARAM , ONLY : NFRE
CHARACTER(LEN=14), INTENT(IN)    :: CDATE
      CHARACTER(LEN=14), INTENT(INOUT) :: CDATEWH
      LOGICAL, INTENT(INOUT)           :: LLNEWFILE
      TYPE(FREQUENCY), INTENT(INOUT) :: WVPRPT
      TYPE(FORCING_FIELDS), INTENT(INOUT)  :: FF_NOW
      TYPE(FORCING_FIELDS), INTENT(IN)     :: FF_NEXT

END SUBROUTINE NEWWIND
end interface
