interface
SUBROUTINE OMEGAGC(KIJS, KIJL, UST, NS, XKS, OMS)
use parkind_wave, only:&
 & jwim,&
 & jwrb
INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: UST
INTEGER(KIND=JWIM), DIMENSION(KIJS:KIJL), INTENT(OUT) :: NS
REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: XKS
REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: OMS
END SUBROUTINE OMEGAGC
end interface
