interface
SUBROUTINE OUTBLOCK (KIJS, KIJL, MIJ,                &
 &                   FL1, XLLWS,                     &
 &                   WAVNUM, CINV, CGROUP,           &
 &                   DEPTH, UCUR, VCUR, IODP,        &
 &                   ALTWH, CALTWH, RALTCOR, USTOKES, VSTOKES, STRNMS, &
 &                   TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD, &
 &                   PHIEPS, PHIAW, &
 &                   AIRD, WDWAVE, CICOVER, WSWAVE, WSTAR, &
 &                   UFRIC, TAUW, Z0M, Z0B, CHRNCK, CITHICK, &
 &                   NEMOSST, NEMOCICOVER, NEMOCITHICK, NEMOUCUR, NEMOVCUR, &
 &                   BOUT)
 use parkind_wave, only:&
 & jwim,&
 & jwrb,JWIM,JWRO
 USE YOWDRVTYPE , ONLY : ENVIRONMENT, FREQUENCY, FORCING_FIELDS, &
 & INTGT_PARAM_FIELDS, OCEAN2WAVE
 use yowcout , only:&
 & niprmout
 USE YOWPARAM , ONLY : NANG ,NFRE
INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      INTEGER(KIND=JWIM), DIMENSION(KIJS:KIJL), INTENT(IN) :: MIJ
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(IN) :: FL1, XLLWS
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL, NFRE), INTENT(IN) :: WAVNUM
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL, NFRE), INTENT(IN) :: CINV
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL, NFRE), INTENT(IN) :: CGROUP

      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: DEPTH
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: UCUR
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: VCUR
      INTEGER(KIND=JWIM), DIMENSION(KIJS:KIJL), INTENT(IN) :: IODP

      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: AIRD, WDWAVE, CICOVER, WSWAVE, WSTAR
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: UFRIC, TAUW, Z0M, Z0B, CHRNCK, CITHICK
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: ALTWH, CALTWH, RALTCOR, USTOKES, VSTOKES, STRNMS
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: PHIEPS, PHIAW
      REAL(KIND=JWRO), DIMENSION(KIJS:KIJL), INTENT(IN) :: NEMOSST, NEMOCICOVER, NEMOCITHICK, NEMOUCUR, NEMOVCUR
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NIPRMOUT), INTENT(OUT) :: BOUT
END SUBROUTINE OUTBLOCK
end interface
