interface
SUBROUTINE OUTBETA (KIJS, KIJL, &
 & U10, USTAR, Z0M, Z0B, CHRNCK, &
 & BETAM , BETAHQ, CD)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: U10
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: USTAR
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: Z0M
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: Z0B
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: CHRNCK
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: BETAM
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: BETAHQ
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT), OPTIONAL :: CD
END SUBROUTINE OUTBETA
end interface
