interface
 SUBROUTINE OUTNAM ( &
 & KNANG, KNFRE, &
 & KNGX, KNGY, KNIBLO, KNOVER, KNGOUT, KNOUTT, &
 & KFRH, MFRSTLW, MLSTHG, &
 & KNMAXC, KNMAXF, KNBINP, KNIBL1, KNIBLD, KNIBLC, &
 & KITAUMAX, KJUMAX, KIUSTAR, KIALPHA, KNDEPTH, KIREFRA, iper)
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM), INTENT(IN) :: &
 & KNANG, KNFRE, &
 & KNGX, KNGY, KNIBLO, KNOVER, KNGOUT, KNOUTT, &
 & KFRH, MFRSTLW, MLSTHG, &
 & KNMAXC, KNMAXF, KNBINP, KNIBL1, KNIBLD, KNIBLC, &
 & KITAUMAX, KJUMAX, KIUSTAR, KIALPHA, KNDEPTH, KIREFRA, iper
 END SUBROUTINE OUTNAM
end interface
