interface
 SUBROUTINE OUTSETWMASK (KIJS, KIJL, IODP, CICVR, BOUT)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 use yowcout , only:&
 & niprmout
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 INTEGER(KIND=JWIM), DIMENSION(KIJS:KIJL), INTENT(IN) :: IODP
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: CICVR
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NIPRMOUT), INTENT(INOUT) :: BOUT
 END SUBROUTINE OUTSETWMASK
end interface
