interface
SUBROUTINE OUTWSPEC (IJS, IJL, SPEC, MARSTYPE, CDATE, CDATED, IFCST)
use parkind_wave, only:&
 & jwim,&
 & jwrb
use yowparam , only:&
 & nang,&
 & nfre
INTEGER(KIND=JWIM), INTENT(IN) :: IJS, IJL
REAL(KIND=JWRB), DIMENSION(IJS:IJL, NANG, NFRE), INTENT(IN) :: SPEC
CHARACTER(LEN=2), INTENT(IN) :: MARSTYPE
CHARACTER(LEN=14), INTENT(IN) :: CDATE, CDATED
INTEGER(KIND=JWIM), INTENT(IN) :: IFCST
END SUBROUTINE OUTWSPEC
end interface
