interface
 SUBROUTINE PACKR (NIN, NOUT, NDIM, IFLAG, RPACK)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: NIN, NDIM
 INTEGER(KIND=JWIM), INTENT(OUT) :: NOUT
 INTEGER(KIND=JWIM), DIMENSION(NDIM), INTENT(INOUT) :: IFLAG
 REAL(KIND=JWRB), DIMENSION(NDIM), INTENT(INOUT) :: RPACK
 END SUBROUTINE PACKR
end interface
