interface
 SUBROUTINE PACKI (NIN, NOUT, NDIM, IFLAG, IPACK)
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM), INTENT(IN) :: NIN, NDIM
 INTEGER(KIND=JWIM), INTENT(OUT) :: NOUT
 INTEGER(KIND=JWIM), DIMENSION(NDIM), INTENT(INOUT) :: IFLAG, IPACK
 END SUBROUTINE PACKI
end interface
