interface
 SUBROUTINE PARMEAN (KIJS, KIJL, NPMAX, NPEAK, &
 & SPEC, &
 & ENE, DIR, PER)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM ,ONLY : NANG, NFRE
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL, NPMAX
 INTEGER(KIND=JWIM), INTENT(IN), DIMENSION(KIJS:KIJL) :: NPEAK
 REAL(KIND=JWRB), INTENT(IN) :: SPEC(NANG,NFRE,NPMAX,KIJS:KIJL)
 REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJS:KIJL,0:NPMAX) :: ENE, DIR, PER
 END SUBROUTINE PARMEAN
end interface
