interface
 SUBROUTINE PEAK (KIJS, KIJL, FETCH, FPMAX, U10, FP, ALPHAJ)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), INTENT(IN) :: FETCH, FPMAX
 REAL(KIND=JWRB),DIMENSION(KIJS:KIJL), INTENT(IN) :: U10
 REAL(KIND=JWRB),DIMENSION(KIJS:KIJL), INTENT(OUT) :: FP
 REAL(KIND=JWRB),DIMENSION(KIJS:KIJL), INTENT(INOUT) :: ALPHAJ
 END SUBROUTINE PEAK
end interface
