interface
 SUBROUTINE PEAKFRI (KIJS, KIJL, F, IPEAKF, EPEAKF, F1D)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM , ONLY : NANG ,NFRE
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), INTENT(IN) :: F(KIJS:KIJL,NANG,NFRE)
 INTEGER(KIND=JWIM), INTENT(OUT) :: IPEAKF(KIJS:KIJL)
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: EPEAKF
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NFRE), INTENT(OUT) :: F1D
 END SUBROUTINE PEAKFRI
end interface
