interface
 SUBROUTINE PEAK_ANG(KIJS, KIJL, FL1, XNU, SIG_TH)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM , ONLY : NANG ,NFRE
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(IN) :: FL1
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: XNU, SIG_TH
 END SUBROUTINE PEAK_ANG
end interface
