interface
SUBROUTINE PRESET_WGRIB_TEMPLATE(CT, IGRIB_HANDLE, NGRIBV, LLCREATE, NBITSPERVALUE)
 use parkind_wave, only:&
 & jwim
 CHARACTER(LEN=1), INTENT(IN) :: CT
 INTEGER(KIND=JWIM), INTENT(OUT) :: IGRIB_HANDLE
 INTEGER, INTENT(IN), OPTIONAL :: NGRIBV
 LOGICAL, INTENT(IN), OPTIONAL :: LLCREATE
 INTEGER(KIND=JWIM) , INTENT(IN), OPTIONAL :: NBITSPERVALUE
END SUBROUTINE PRESET_WGRIB_TEMPLATE
end interface
