interface
SUBROUTINE PROPDOT(KIJS, KIJL, NINF, NSUP,                &
     &                   BLK2GLO,                               &
     &                   WAVNUM_EXT, CGROUP_EXT, OMOSNH2KD_EXT, &
     &                   COSPHM1_EXT, DEPTH_EXT, U_EXT, V_EXT,  &
     &                   THDC, THDD, SDOT)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWDRVTYPE , ONLY : WVGRIDGLO
 USE YOWPARAM , ONLY : NIBLO ,NANG ,NFRE_RED
INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL, NINF, NSUP
      TYPE(WVGRIDGLO), INTENT(IN) :: BLK2GLO
      REAL(KIND=JWRB), DIMENSION(NINF:NSUP+1, NFRE_RED), INTENT(IN) :: WAVNUM_EXT, CGROUP_EXT, OMOSNH2KD_EXT
      REAL(KIND=JWRB), DIMENSION(NINF:NSUP+1), INTENT(IN) :: COSPHM1_EXT, DEPTH_EXT, U_EXT, V_EXT
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL, NANG), INTENT(INOUT) :: THDC, THDD
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL, NANG, NFRE_RED), INTENT(INOUT) :: SDOT
 END SUBROUTINE PROPDOT
end interface
