interface
SUBROUTINE PROPAGS2 (F1, F3, NINF, NSUP, KIJS, KIJL, NANG, ND3S, ND3E)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 REAL(KIND=JWRB),DIMENSION(NINF:NSUP+1, NANG, ND3S:ND3E), INTENT(IN) :: F1
 REAL(KIND=JWRB),DIMENSION(NINF:NSUP+1, NANG, ND3S:ND3E), INTENT(OUT) :: F3
 INTEGER(KIND=JWIM), INTENT(IN) :: NINF, NSUP
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 INTEGER(KIND=JWIM), INTENT(IN) :: NANG, ND3S, ND3E
END SUBROUTINE PROPAGS2
end interface
