interface
 SUBROUTINE READWGRIB(IU06, FILNM, IPARAM, CDATE,        &
     &                     BLK2LOC,                           &
     &                     NXS, NXE, NYS, NYE, FIELDG,        &
     &                     CD, KZLEV, LLONLYPOS, IREAD, FIELD )
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWDRVTYPE , ONLY : FORCING_FIELDS,WVGRIDLOC
 USE YOWGRID , ONLY : NPROMA_WAM, NCHNK
    INTEGER(KIND=JWIM), INTENT(IN) :: IU06
      CHARACTER(LEN=24), INTENT(IN) :: FILNM
      INTEGER(KIND=JWIM), INTENT(IN) :: IPARAM
      CHARACTER(LEN=14), INTENT(IN) :: CDATE
      TYPE(WVGRIDLOC), INTENT(IN) :: BLK2LOC
      INTEGER(KIND=JWIM), INTENT(IN) :: NXS, NXE, NYS, NYE
      TYPE(FORCING_FIELDS), INTENT(IN) :: FIELDG
      TYPE(FORCING_FIELDS), INTENT(INOUT), OPTIONAL :: FIELD
      REAL(KIND=JWRB), DIMENSION(NPROMA_WAM, NCHNK), INTENT(INOUT) :: CD
      INTEGER(KIND=JWIM), INTENT(INOUT) :: KZLEV
      LOGICAL, INTENT(IN) :: LLONLYPOS
      INTEGER(KIND=JWIM), INTENT(IN) :: IREAD
 END SUBROUTINE READWGRIB
end interface
