interface
 SUBROUTINE READSTA (IUIN, CBDT, CEDT, ANALPD, FOREPD, IS, &
 & CRSDT, CLSDT, CABDT, CAEDT, IASS, NF, ISTAT, &
 & CCURA, LRSTPARAL, NPROC_RST )
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM), INTENT(IN) :: IUIN
 INTEGER(KIND=JWIM), INTENT(OUT) :: ANALPD, FOREPD, IS, IASS, NF
 INTEGER(KIND=JWIM), INTENT(OUT) :: NPROC_RST
 INTEGER(KIND=JWIM), INTENT(OUT) :: ISTAT(3)
 CHARACTER(LEN=14), INTENT(OUT) :: CBDT, CEDT
 CHARACTER(LEN=14), INTENT(OUT) :: CRSDT, CLSDT, CABDT, CAEDT
 CHARACTER(LEN=14), INTENT(OUT) :: CCURA
 LOGICAL, INTENT(OUT) :: LRSTPARAL
 END SUBROUTINE READSTA
end interface
