interface
 SUBROUTINE ROTSPEC (NFRE, NANG, ML, KL, F1, F3, RTHET)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: NFRE, NANG, ML, KL
 REAL(KIND=JWRB), INTENT(IN) :: RTHET
 REAL(KIND=JWRB), DIMENSION(NANG,NFRE), INTENT(IN) :: F1
 REAL(KIND=JWRB), DIMENSION(NANG,NFRE), INTENT(OUT) :: F3
 END SUBROUTINE ROTSPEC
end interface
