interface
 SUBROUTINE SCOSFL (KIJS, KIJL, F, MM, MEANCOSFL)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM , ONLY : NANG ,NFRE
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL, NANG, NFRE), INTENT(IN) :: F
 INTEGER(KIND=JWIM), DIMENSION(KIJS:KIJL), INTENT(IN) :: MM
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: MEANCOSFL
 END SUBROUTINE SCOSFL
end interface
