interface
 SUBROUTINE SECSPOM(F1,F3,KIJS,KIJL,NFRE,NANG,NMAX,NDEPTH,DEPTHA, &
 & DEPTHD,OMSTART,FRAC,MR,DFDTH,OMEGA,DEPTH, &
 & AKMEAN,TA,TB,TC_QL,TT_4M,TT_4P,IM_P,IM_M)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM),INTENT(IN) :: KIJS,KIJL,NFRE,NANG,NMAX,NDEPTH,MR
 INTEGER(KIND=JWIM),DIMENSION(NFRE,NFRE), INTENT(IN) :: IM_P, IM_M
 REAL(KIND=JWRB), INTENT(IN) :: DEPTHA, DEPTHD, OMSTART, FRAC
 REAL(KIND=JWRB), DIMENSION(NFRE), INTENT(IN) :: OMEGA, DFDTH
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: DEPTH, AKMEAN
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(IN) :: F1
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(OUT) :: F3
 REAL(KIND=JWRB), DIMENSION(NDEPTH,NANG,NFRE,NFRE), INTENT(IN) :: TA,TB,TC_QL,TT_4M,TT_4P
 END SUBROUTINE SECSPOM
end interface
