interface
 SUBROUTINE SEMEAN (FL1, KIJS, KIJL, EM, LLEPSMIN)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM , ONLY : NANG ,NFRE
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL, NANG, NFRE), INTENT(IN) :: FL1
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: EM
 LOGICAL, INTENT(IN) :: LLEPSMIN
 END SUBROUTINE SEMEAN
end interface
