interface
 SUBROUTINE SEPWISW (KIJS, KIJL, MIJ, FL1, XLLWS, CINV, &
 & UFRIC ,WSWAVE ,WDWAVE, COSWDIF, &
 & ESWELL ,FSWELL ,THSWELL , &
 & P1SWELL ,P2SWELL ,SPRDSWELL, &
 & ESEA ,FSEA ,THWISEA , &
 & P1SEA ,P2SEA ,SPRDSEA , &
 & EMTRAIN ,THTRAIN ,PMTRAIN)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 use yowcout , only:&
 & ntrain
 use yowparam , only:&
 & nang,&
 & nfre
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 INTEGER(KIND=JWIM), DIMENSION(KIJS:KIJL), INTENT(IN) :: MIJ
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(IN) :: FL1
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(IN) :: XLLWS
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NFRE), INTENT(IN) :: CINV
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: UFRIC, WSWAVE, WDWAVE
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG), INTENT(IN) :: COSWDIF
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: ESWELL ,FSWELL ,THSWELL, P1SWELL, P2SWELL, SPRDSWELL
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: ESEA ,FSEA ,THWISEA, P1SEA , P2SEA , SPRDSEA
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NTRAIN), INTENT(OUT) :: EMTRAIN, THTRAIN, PMTRAIN
 END SUBROUTINE SEPWISW
end interface
