interface
 SUBROUTINE SKEWNESS(IU06,F1,NCOLL,XKAPPA1,DELH_ALT)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM , ONLY : NANG ,NFRE
 INTEGER(KIND=JWIM), INTENT(IN) :: IU06, NCOLL
 REAL(KIND=JWRB), DIMENSION(NCOLL), INTENT(OUT) :: XKAPPA1, DELH_ALT
 REAL(KIND=JWRB), DIMENSION(NCOLL,NANG,NFRE), INTENT(IN) :: F1
 END SUBROUTINE SKEWNESS
end interface
