interface
SUBROUTINE SPECTRA (KIJS, KIJL, ZGAMMA, SA, SB, FP, ALPHAJ, THES, FL1)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM , ONLY : NANG ,NFRE
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), INTENT(IN) :: ZGAMMA, SA, SB
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN):: FP, ALPHAJ, THES
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(OUT):: FL1
END SUBROUTINE SPECTRA
end interface
