interface
REAL(KIND=JWRB) FUNCTION STRESS_GC(ANG_GC, USTAR, Z0, Z0MIN, HALP, RNFAC)
 use parkind_wave, only:&
 & jwrb
 REAL(KIND=JWRB), INTENT(IN) :: ANG_GC
 REAL(KIND=JWRB), INTENT(IN) :: USTAR
 REAL(KIND=JWRB), INTENT(IN) :: Z0
 REAL(KIND=JWRB), INTENT(IN) :: Z0MIN
 REAL(KIND=JWRB), INTENT(IN) :: HALP
 REAL(KIND=JWRB), INTENT(IN) :: RNFAC
END FUNCTION STRESS_GC
end interface
