interface
 SUBROUTINE STRSPEC (NFRE, NANG, ML, KL, FR, FL, GAMMA)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: NFRE, NANG, ML, KL
 REAL(KIND=JWRB), INTENT(IN) :: GAMMA
 REAL(KIND=JWRB), DIMENSION(NFRE), INTENT(IN) :: FR
 REAL(KIND=JWRB), DIMENSION(NANG,NFRE), INTENT(INOUT) :: FL
 END SUBROUTINE STRSPEC
end interface
