interface
 SUBROUTINE TABLES_2ND(NFRE,NANG,NDEPTH,OMSTART,FRAC,XMR, &
 & DFDTH,OMEGA,TH,TA,TB,TC_QL, &
 & TT_4M,TT_4P,IM_P,IM_M,TFAK)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: NFRE, NANG, NDEPTH
 INTEGER(KIND=JWIM), DIMENSION(NFRE,NFRE), INTENT(OUT) :: IM_P, IM_M
 REAL(KIND=JWRB), INTENT(IN) :: OMSTART, FRAC, XMR
 REAL(KIND=JWRB), DIMENSION(NFRE), INTENT(IN) :: DFDTH, OMEGA
 REAL(KIND=JWRB), DIMENSION(NANG), INTENT(IN) :: TH
 REAL(KIND=JWRB), DIMENSION(NDEPTH,NANG,NFRE,NFRE), INTENT(OUT) :: TA,TB,TC_QL,TT_4M,TT_4P
 REAL(KIND=JWRB), DIMENSION(NFRE,NDEPTH), INTENT(OUT) :: TFAK
 END SUBROUTINE TABLES_2ND
end interface
