interface
SUBROUTINE TAUT_Z0(KIJS, KIJL, IUSFG, &
& HALP, UTOP, UDIR, TAUW, TAUWDIR, RNFAC, &
& USTAR, Z0, Z0B, CHRNCK)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM , ONLY : NANG ,NFRE
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL, IUSFG
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: HALP, UTOP, UDIR, TAUW, TAUWDIR, RNFAC
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(INOUT) :: USTAR
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: Z0, Z0B, CHRNCK
END SUBROUTINE TAUT_Z0
end interface
