interface
 SUBROUTINE UIBOU (IU05, IU06, CDATEA, CDATEE, IDELPRF, &
 & CDATES, IDELFI, USERID, &
 & RUNDI, FILEDI, PATHI, RUNDO, FILEDO, PATHO, &
 & LREAL, LSWAN)
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM) :: IU05, IU06, IDELPRF, IDELFI
 CHARACTER(LEN=3) :: USERID, RUNDI, FILEDI, RUNDO, FILEDO
 CHARACTER(LEN=14) :: CDATEA, CDATEE, CDATES
 CHARACTER(LEN=60) :: PATHI, PATHO
 LOGICAL :: LREAL, LSWAN
 END SUBROUTINE UIBOU
end interface
