interface
SUBROUTINE UNSETICE(KIJS, KIJL, DEPTH, EMAXDPT, WDWAVE, WSWAVE, CICOVER, FL1)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWDRVTYPE , ONLY : ENVIRONMENT, FORCING_FIELDS
 use yowparam , only:&
 & nang,&
 & nfre
INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: DEPTH, EMAXDPT
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: WDWAVE, WSWAVE, CICOVER
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(INOUT) :: FL1
END SUBROUTINE UNSETICE
end interface
