interface
SUBROUTINE W_MAXH (KIJS, KIJL, F, DEPTH, WAVNUM, &
 & CMAX_F, HMAX_N, CMAX_ST, HMAX_ST, PHIST)
use parkind_wave, only:&
 & jwim,&
 & jwrb
USE YOWPARAM , ONLY : NANG ,NFRE
INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(IN) :: F
REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: DEPTH
REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NFRE), INTENT(IN) :: WAVNUM
REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: CMAX_F
REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: HMAX_N
REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: CMAX_ST
REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: HMAX_ST
REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: PHIST
END SUBROUTINE W_MAXH
end interface
