interface
 SUBROUTINE WAM_NPROMA(IJS, IJL, MTHREADS, NPROMA)
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM), INTENT(IN) :: IJS, IJL, MTHREADS
 INTEGER(KIND=JWIM), INTENT(INOUT) :: NPROMA
 END SUBROUTINE WAM_NPROMA
end interface
