interface
 SUBROUTINE WAM_SORTI (IARRAY, INDEX, N)
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM), INTENT(IN) :: N
 INTEGER(KIND=JWIM), DIMENSION(N), INTENT(INOUT) :: IARRAY
 INTEGER(KIND=JWIM), DIMENSION(N), INTENT(IN) :: INDEX
 END SUBROUTINE WAM_SORTI
end interface
