interface
 SUBROUTINE WAM_SORTINI (IARRAY, INDEX, N)
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM), INTENT(IN) :: N
 INTEGER(KIND=JWIM), DIMENSION(N), INTENT(IN) :: IARRAY
 INTEGER(KIND=JWIM), DIMENSION(N), INTENT(OUT) :: INDEX
 END SUBROUTINE WAM_SORTINI
end interface
