interface
SUBROUTINE WAMADSWSTAR(NXS, NXE, NYS, NYE, FIELDG,            &
 &                     BLK2LOC, FF_NOW)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWDRVTYPE , ONLY : WVGRIDLOC, FORCING_FIELDS
 USE YOWGRID , ONLY : NPROMA_WAM, NCHNK
INTEGER(KIND=JWIM), INTENT(IN) :: NXS, NXE, NYS, NYE
      TYPE(FORCING_FIELDS), INTENT(IN) :: FIELDG
      TYPE(WVGRIDLOC), INTENT(IN) :: BLK2LOC
      TYPE(FORCING_FIELDS), INTENT(INOUT) :: FF_NOW
END SUBROUTINE WAMADSWSTAR
end interface
