interface
SUBROUTINE WDFLUXES (KIJS, KIJL,                 &
     &                     MIJ,                        &
     &                     FL1, XLLWS,                 &
     &                     WAVNUM,CINV,XK2CG,STOKFAC,  &
     &                     DEPTH, INDEP,        &
     &                     AIRD, WDWAVE, CICOVER, WSWAVE, WSTAR, &
     &                     UFRIC, Z0M, Z0B, CHRNCK, CITHICK, &
     &                     WSEMEAN, WSFMEAN, USTOKES, VSTOKES, STRNMS, &
     &                     TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC, PHIOCD, &
     &                     PHIEPS, PHIAW, &
     &                     NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN, &
     &                     NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX, &
     &                     NEMOTAUY, NEMOWSWAVE, NEMOPHIF)
 use parkind_wave, only:&
 & jwim,&
 & jwrb,JWIM,JWRO
 USE YOWDRVTYPE , ONLY : ENVIRONMENT, FREQUENCY, FORCING_FIELDS, &
 & INTGT_PARAM_FIELDS, WAVE2OCEAN
 USE YOWPARAM , ONLY : NANG ,NFRE
INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
      INTEGER(KIND=JWIM),  DIMENSION(KIJS:KIJL), INTENT(OUT) :: MIJ

      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(INOUT) :: FL1
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL, NFRE), INTENT(IN) :: WAVNUM
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL, NFRE), INTENT(IN) :: CINV
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL, NFRE), INTENT(IN) :: XK2CG
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL, NFRE), INTENT(IN) :: STOKFAC
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: DEPTH
      INTEGER(KIND=JWIM), DIMENSION(KIJS:KIJL), INTENT(IN) :: INDEP
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(INOUT) :: AIRD, WDWAVE, CICOVER, WSWAVE, WSTAR
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(INOUT) :: UFRIC, Z0M, Z0B, CHRNCK, CITHICK
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(INOUT) :: TAUXD, TAUYD, TAUOCXD, TAUOCYD, TAUOC
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(INOUT) :: PHIOCD, PHIEPS, PHIAW, USTOKES, VSTOKES
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(INOUT) :: WSEMEAN, WSFMEAN, STRNMS
      REAL(KIND=JWRO), DIMENSION(KIJS:KIJL), INTENT(INOUT) :: NEMOUSTOKES, NEMOVSTOKES, NEMOSTRN
      REAL(KIND=JWRO), DIMENSION(KIJS:KIJL), INTENT(INOUT) :: NPHIEPS, NTAUOC, NSWH, NMWP, NEMOTAUX
      REAL(KIND=JWRO), DIMENSION(KIJS:KIJL), INTENT(INOUT) :: NEMOTAUY, NEMOWSWAVE, NEMOPHIF
      REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(OUT) :: XLLWS
END SUBROUTINE WDFLUXES
end interface
