interface
 SUBROUTINE WDIRSPREAD (KIJS, KIJL, F, EMEAN, LLPEAKF, WDIRSPRD)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 USE YOWPARAM , ONLY : NANG ,NFRE
 USE, INTRINSIC :: IEEE_EXCEPTIONS
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL,NANG,NFRE), INTENT(IN) :: F
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: EMEAN
 LOGICAL, INTENT(IN) :: LLPEAKF
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: WDIRSPRD
 END SUBROUTINE WDIRSPREAD
end interface
