interface
 SUBROUTINE WGRIB2FDB (KUSO, KTEST, &
 & IGRIB_HANDLE, KLEN, KGRIB, &
 & KERR)
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM), INTENT(IN) :: KUSO, KTEST, IGRIB_HANDLE
 INTEGER(KIND=JWIM), INTENT(IN) :: KLEN
 INTEGER(KIND=JWIM), INTENT(OUT) :: KERR
 INTEGER(KIND=JWIM), DIMENSION(KLEN), INTENT(INOUT) :: KGRIB
 END SUBROUTINE WGRIB2FDB
end interface
