interface
SUBROUTINE WGRIBENOUT (IU06, ITEST, I1, I2, FIELD, &
 & ITABLE, IPARAM, KLEV, IK, IM, &
 & CDATE, IFCST, MARSTYPE, LFDB, IU)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: IU06, ITEST, I1, I2
 INTEGER(KIND=JWIM), INTENT(IN) :: ITABLE, IPARAM, KLEV, IK, IM
 INTEGER(KIND=JWIM), INTENT(IN) :: IFCST
 INTEGER(KIND=JWIM), INTENT(IN) :: IU
 REAL(KIND=JWRB), INTENT(INOUT) :: FIELD(I1,I2)
 CHARACTER(LEN=2), INTENT(IN) :: MARSTYPE
 CHARACTER(LEN=14), INTENT(IN) :: CDATE
 LOGICAL, INTENT(IN) :: LFDB
END SUBROUTINE WGRIBENOUT
end interface
