interface
 SUBROUTINE WGRIBOUT (IU06, ITEST, LFDB, IU, IGRIB_HANDLE, ISIZE, KGRIB_BUFR)
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM), INTENT(IN) :: IGRIB_HANDLE, ISIZE
 INTEGER(KIND=JWIM), INTENT(IN) :: IU06, ITEST, IU
 INTEGER(KIND=JWIM), DIMENSION(ISIZE), INTENT(INOUT) :: KGRIB_BUFR
 LOGICAL, INTENT(IN) :: LFDB
 END SUBROUTINE WGRIBOUT
end interface
