interface
SUBROUTINE WGRIBENCODE ( IU06, ITEST, &
& I1, I2, &
& FIELD, &
& ITABLE, IPARAM, &
& KLEV, &
& IK, IM, &
& CDATE, IFCST, MARSTYPE, &
& PPMISS, PPEPS, PPREC, PPRESOL, PPMIN_RESET, NTENCODE, &
& LGRHDIFS, &
& NDATE_TIME_WINDOW_END, &
& NGRBRESS, LNEWLVTP, LPADPOLES, &
& NLONRGG_SIZE, NLONRGG, IRGG, &
& AMONOP, AMOSOP, XDELLA, CLDOMAIN, &
& KCOUSTEP, LRSTST0, &
& ZMISS, &
& IGRIB_HANDLE)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: IU06, ITEST, I1, I2
 INTEGER(KIND=JWIM), INTENT(IN) :: ITABLE, IPARAM, KLEV, IK, IM, IFCST
 INTEGER(KIND=JWIM), INTENT(INOUT) :: IGRIB_HANDLE
 REAL(KIND=JWRB), INTENT(INOUT) :: FIELD(I1,I2)
 CHARACTER(LEN=2), INTENT(IN) :: MARSTYPE
 CHARACTER(LEN=14), INTENT(IN) :: CDATE
 LOGICAL, INTENT(IN) :: LGRHDIFS
 REAL(KIND=JWRB), INTENT(IN) :: PPMISS
 REAL(KIND=JWRB), INTENT(IN) :: PPEPS
 REAL(KIND=JWRB), INTENT(IN) :: PPREC
 REAL(KIND=JWRB), INTENT(IN) :: PPRESOL
 REAL(KIND=JWRB), INTENT(IN) :: PPMIN_RESET
 INTEGER(KIND=JWIM), INTENT(IN) :: NTENCODE
 INTEGER(KIND=JWIM), INTENT(IN) :: NDATE_TIME_WINDOW_END
 INTEGER(KIND=JWIM), INTENT(IN) :: NGRBRESS
 LOGICAL, INTENT(IN) :: LNEWLVTP
 LOGICAL, INTENT(IN) :: LPADPOLES
 INTEGER(KIND=JWIM), INTENT(IN) :: NLONRGG_SIZE
 INTEGER(KIND=JWIM), INTENT(IN) :: NLONRGG(NLONRGG_SIZE)
 INTEGER(KIND=JWIM), INTENT(IN) :: IRGG
 REAL(KIND=JWRB), INTENT(IN) :: AMONOP
 REAL(KIND=JWRB), INTENT(IN) :: AMOSOP
 REAL(KIND=JWRB), INTENT(IN) :: XDELLA
 CHARACTER(LEN=1), INTENT(IN) :: CLDOMAIN
 INTEGER(KIND=JWIM), INTENT(IN) :: KCOUSTEP
 LOGICAL, INTENT(IN) :: LRSTST0
 REAL(KIND=JWRB), INTENT(IN) :: ZMISS
END SUBROUTINE WGRIBENCODE
end interface
