interface
 SUBROUTINE WPOSNAM(KULNAM, CDNAML, LDEOF)
 USE PARKIND_WAVE, ONLY : JWIM
 LOGICAL, INTENT(OUT) :: LDEOF
 INTEGER(KIND=JWIM), INTENT(IN) :: KULNAM
 CHARACTER(LEN=*), INTENT(IN) :: CDNAML
 END SUBROUTINE WPOSNAM
end interface
