interface
 SUBROUTINE WRITSTA (IDIN, CBDT, CEDT, ANALPD, FOREPD, IS, &
 & CRSDT, CLSDT, CABDT, CAEDT, IASS, NF, ISTAT, &
 & CCURA, LRSTPARAL, NPROC_RST )
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM), INTENT(IN) :: IDIN, IS, IASS, NF
 INTEGER(KIND=JWIM), INTENT(IN) :: ANALPD, FOREPD
 INTEGER(KIND=JWIM), INTENT(IN) :: ISTAT(3)
 INTEGER(KIND=JWIM), INTENT(IN) :: NPROC_RST
 CHARACTER(LEN=14), INTENT(IN) :: CBDT,CEDT,CABDT,CAEDT,CRSDT,CLSDT
 CHARACTER(LEN=14), INTENT(IN) :: CCURA
 LOGICAL, INTENT(IN) :: LRSTPARAL
 END SUBROUTINE WRITSTA
end interface
