interface
 SUBROUTINE WRITESTRESS(IJINF, IJSUP, NREAL, RFIELD, FILENAME, LRSTPARAL)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: IJINF, IJSUP, NREAL
 REAL(KIND=JWRB),DIMENSION(IJINF:IJSUP,NREAL),INTENT(INOUT) :: RFIELD
 CHARACTER(LEN=296), INTENT(IN) :: FILENAME
 LOGICAL, INTENT(IN) :: LRSTPARAL
 END SUBROUTINE WRITESTRESS
end interface
