interface
 SUBROUTINE WSMFEN (FSEA, EW, FM, USTT, DPT)
 use parkind_wave, only:&
 & jwrb
 USE YOWPARAM , ONLY : NANG ,NFRE
 REAL(KIND=JWRB), INTENT(IN) :: USTT, DPT
 REAL(KIND=JWRB), DIMENSION(NANG,NFRE), INTENT(IN) :: FSEA
 REAL(KIND=JWRB), INTENT(OUT) :: EW, FM
 END SUBROUTINE WSMFEN
end interface
