interface
 SUBROUTINE WSTREAM_STRG(ISTREAM,CSTREAM,NENSFNB,NTOTENS, &
 & MARSFCTYPE, KSTREAM, LASTREAM)
 use parkind_wave, only:&
 & jwim
 INTEGER(KIND=JWIM), INTENT(IN) :: ISTREAM, NENSFNB, NTOTENS
 INTEGER(KIND=JWIM), INTENT(OUT) :: KSTREAM
 CHARACTER(LEN=2), INTENT(OUT) :: MARSFCTYPE
 CHARACTER(LEN=4), INTENT(OUT) :: CSTREAM
 LOGICAL, INTENT(OUT) :: LASTREAM
 END SUBROUTINE WSTREAM_STRG
end interface
