interface
 SUBROUTINE WVFRICVELO(KIJS, KIJL, U10, BETA, G, XKAPPA, ZREF, &
 & USTAR, Z0W)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB), INTENT(IN) :: G, XKAPPA, ZREF
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(IN) :: U10, BETA
 REAL(KIND=JWRB), DIMENSION(KIJS:KIJL), INTENT(OUT) :: USTAR, Z0W
 END SUBROUTINE WVFRICVELO
end interface
