interface
 SUBROUTINE WVWAMINIT (LLCOUPLED, IULOG, LLRNL, &
 & NGAUSSW, NLON, NLAT, RSOUTW, RNORTW)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: IULOG
 INTEGER(KIND=JWIM), INTENT(OUT) :: NGAUSSW, NLON, NLAT
 REAL(KIND=JWRB), INTENT(OUT) :: RSOUTW, RNORTW
 LOGICAL, INTENT(IN) :: LLRNL
 LOGICAL, INTENT(IN) :: LLCOUPLED
 END SUBROUTINE WVWAMINIT
end interface
