interface
 SUBROUTINE Z0WAVE (KIJS, KIJL, US, TAUW, UTOP, Z0, Z0B, CHRNCK)
 use parkind_wave, only:&
 & jwim,&
 & jwrb
 INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL
 REAL(KIND=JWRB),DIMENSION(KIJS:KIJL),INTENT(IN) :: US, TAUW, UTOP
 REAL(KIND=JWRB),DIMENSION(KIJS:KIJL),INTENT(OUT) :: Z0, Z0B, CHRNCK
 END SUBROUTINE Z0WAVE
end interface
