! (C) Copyright 1989- ECMWF.
!
! This software is licensed under the terms of the Apache Licence Version 2.0
! which can be obtained at http://www.apache.org/licenses/LICENSE-2.0.
! In applying this licence, ECMWF does not waive the privileges and immunities
! granted to it by virtue of its status as an intergovernmental organisation
! nor does it submit to any jurisdiction.
!
MODULE SINFLX_SCC_MOD
  CONTAINS
  SUBROUTINE SINFLX_SCC (ICALL, KIJS, KIJL, LUPDTUS, FL1, WAVNUM, CINV, XK2CG, WSWAVE, WDWAVE, AIRD, RAORW, WSTAR, CICOVER,  &
  & COSWDIF, SINWDIF2, FMEAN, HALP, FMEANWS, FLM, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, PHIWA, FLD, SL, SPOS, MIJ, RHOWGDFTH,  &
  & XLLWS)
    
    ! ----------------------------------------------------------------------
    
    !**** *SINFLX* - UPDATE STRESS AND COMPUTE WIND INPUT SOURCE TERM.
    
    ! ----------------------------------------------------------------------
    
    USE STRESSO_SCC_MOD, ONLY: STRESSO_SCC
    USE SINPUT_SCC_MOD, ONLY: SINPUT_SCC
    USE HALPHAP_SCC_MOD, ONLY: HALPHAP_SCC
    USE FRCUTINDEX_SCC_MOD, ONLY: FRCUTINDEX_SCC
    USE FEMEANWS_SCC_MOD, ONLY: FEMEANWS_SCC
    USE AIRSEA_SCC_MOD, ONLY: AIRSEA_SCC
    USE PARKIND_WAVE, ONLY: JWIM, JWRB, JWRU
    
    USE YOWCOUP, ONLY: LWCOU, LLCAPCHNK, LLGCBZ0, LLNORMAGAM
    USE YOWPARAM, ONLY: NANG, NFRE
    USE YOWPHYS, ONLY: DTHRN_A, DTHRN_U
    USE YOWWNDG, ONLY: ICODE, ICODE_CPL
    
    
    ! ----------------------------------------------------------------------
    
    IMPLICIT NONE
    INTEGER(KIND=JWIM), INTENT(IN) :: ICALL    !! CALL NUMBER.
    INTEGER(KIND=JWIM), INTENT(IN) :: KIJS, KIJL    !! GRID POINT INDEXES.
    
    LOGICAL, INTENT(IN) :: LUPDTUS    !! IF TRUE UFRIC AND Z0M WILL BE UPDATED (CALLING AIRSEA).
    
    REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL, NANG, NFRE) :: FL1    !! WAVE SPECTRUM.
    REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: WAVNUM    !! WAVE NUMBER.
    REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: CINV    !! INVERSE PHASE VELOCITY.
    REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NFRE) :: XK2CG    !! (WAVNUM)**2 * GROUP SPPED.
    REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: WSWAVE    !! WIND SPEED IN M/S.
    REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WDWAVE    !! WIND DIRECTION IN RADIANS IN OCEANOGRAPHIC NOTATION.
    REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: AIRD    !! AIR DENSITY (KG/M**3).
    REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: RAORW    !! RATIO AIR DENSITY TO WATER DENSITY.
    REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: WSTAR    !! FREE CONVECTION VELOCITY SCALE (M/S)
    REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: CICOVER    !! SEA ICE COVER.
    REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: COSWDIF    !! COS(TH(K)-WDWAVE(IJ))
    REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: SINWDIF2    !! SIN(TH(K)-WDWAVE(IJ))**2
    REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL) :: FMEAN    !! MEAN FREQUENCY.
    REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: HALP    !! 1/2 PHILLIPS PARAMETER
    REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: FMEANWS    !! MEAN FREQUENCY OF THE WINDSEA.
    REAL(KIND=JWRB), INTENT(IN), DIMENSION(KIJL, NANG) :: FLM    !! SPECTAL DENSITY MINIMUM VALUE
    REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: UFRIC    !! FRICTION VELOCITY IN M/S.
    REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: TAUW    !! WAVE STRESS IN (M/S)**2
    REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: TAUWDIR    !! WAVE STRESS DIRECTION.
    REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: Z0M    !! ROUGHNESS LENGTH IN M.
    REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: Z0B    !! BACKGROUND ROUGHNESS LENGTH.
    REAL(KIND=JWRB), INTENT(INOUT), DIMENSION(KIJL) :: CHRNCK    !! CHARNOCK COEFFICIENT.
    
    REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL) :: PHIWA    !! ENERGY FLUX FROM WIND INTO WAVES.
    REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: FLD    !! DIAGONAL MATRIX OF FUNCTIONAL DERIVATIVE.
    REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: SL    !! TOTAL SOURCE FUNCTION ARRAY.
    REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: SPOS    !!  POSITIVE SINPUT ONLY.
    
    INTEGER(KIND=JWIM), INTENT(OUT) :: MIJ(KIJL)    !! LAST FREQUENCY INDEX OF THE PROGNOSTIC RANGE.
    
    REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NFRE) :: RHOWGDFTH    !! WATER DENSITY * G * DF * DTHETA
    
    REAL(KIND=JWRB), INTENT(OUT), DIMENSION(KIJL, NANG, NFRE) :: XLLWS    !! TOTAL WINDSEA MASK FROM INPUT SOURCE TERM.
    
    
    INTEGER(KIND=JWIM) :: IJ, K
    INTEGER(KIND=JWIM) :: IUSFG, ICODE_WND
    INTEGER(KIND=JWIM) :: NGST
    
    REAL(KIND=JWRB), DIMENSION(KIJL) :: RNFAC
    
    LOGICAL :: LLPHIWA, LLSNEG
!$acc routine vector
!$acc data present( FL1, WAVNUM, CINV, XK2CG, WSWAVE, WDWAVE, AIRD, RAORW, WSTAR, CICOVER, COSWDIF, SINWDIF2, FMEAN, HALP,  &
!$acc & FMEANWS, FLM, UFRIC, TAUW, TAUWDIR, Z0M, Z0B, CHRNCK, PHIWA, FLD, SL, SPOS, MIJ, RHOWGDFTH, XLLWS )
    
    ! ----------------------------------------------------------------------
    
    
    ! UPDATE UFRIC AND Z0M
    IF (ICALL == 1) THEN
      IUSFG = 0
      IF (LWCOU) THEN
        ICODE_WND = ICODE_CPL
      ELSE
        ICODE_WND = ICODE
      END IF
      
      LLPHIWA = .false.
      LLSNEG = .false.
    ELSE
      IUSFG = 1
      ICODE_WND = 3
      
      LLPHIWA = .true.
      LLSNEG = .true.
    END IF
!$loki separator
    
!$acc loop vector
    DO IJ=KIJS,KIJL
      
      IF (LLNORMAGAM .and. LLCAPCHNK) THEN
        RNFAC(IJ) = 1.0_JWRB + DTHRN_A*(1.0_JWRB + TANH(WSWAVE(IJ) - DTHRN_U))
      ELSE
        RNFAC(IJ) = 1.0_JWRB
      END IF
      
      
    END DO
    IF (LUPDTUS) THEN
      ! increase noise level in the tail
      IF (ICALL == 1) THEN
        
!$acc loop vector
        DO IJ=KIJS,KIJL
!$acc loop seq
          DO K=1,NANG
            FL1(IJ, K, NFRE) = MAX(FL1(IJ, K, NFRE), FLM(IJ, K))
          END DO
          
        END DO
        IF (LLGCBZ0) THEN
          CALL HALPHAP_SCC(KIJS, KIJL, WAVNUM, COSWDIF, FL1, HALP)
        ELSE
          
!$acc loop vector
          DO IJ=KIJS,KIJL
            HALP(IJ) = 0.0_JWRB
          END DO
        END IF
        
      END IF
      
      CALL AIRSEA_SCC(KIJS, KIJL, HALP, WSWAVE, WDWAVE, TAUW, TAUWDIR, RNFAC, UFRIC, Z0M, Z0B, CHRNCK, ICODE_WND, IUSFG)
      
    END IF
    
    ! COMPUTE WIND INPUT
    !!  FLD AND SL ARE INITIALISED IN SINPUT
    
    CALL SINPUT_SCC(ICALL, LLSNEG, KIJS, KIJL, FL1, WAVNUM, CINV, XK2CG, WDWAVE, WSWAVE, UFRIC, Z0M, COSWDIF, SINWDIF2, RAORW,  &
    & WSTAR, RNFAC, FLD, SL, SPOS, XLLWS)
    
    
    ! MEAN FREQUENCY CHARACTERISTIC FOR WIND SEA
    CALL FEMEANWS_SCC(KIJS, KIJL, FL1, XLLWS, FMEANWS)
    
    ! COMPUTE LAST FREQUENCY INDEX OF PROGNOSTIC PART OF SPECTRUM.
    CALL FRCUTINDEX_SCC(KIJS, KIJL, FMEAN, FMEANWS, UFRIC, CICOVER, MIJ, RHOWGDFTH)
    
    ! UPDATE TAUW
    CALL STRESSO_SCC(KIJS, KIJL, MIJ, RHOWGDFTH, FL1, SL, SPOS, CINV, WDWAVE, UFRIC, Z0M, AIRD, RNFAC, COSWDIF, SINWDIF2, TAUW,  &
    & TAUWDIR, PHIWA, LLPHIWA)
    
    ! ----------------------------------------------------------------------
    
    
!$acc end data
  END SUBROUTINE SINFLX_SCC
END MODULE SINFLX_SCC_MOD
